FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Install additional packages
RUN sudo apt update && sudo apt -y install \
    libnss3-dev \
    libgdk-pixbuf2.0-dev \
    libgtk-3-dev \
    libxss-dev \
    libasound2 \
    dbus-x11 \
    dbus 
